%YAML:1.0
---
camera1_id: 0
camera2_id: 1
camera1_settings:
   h_max: 126
   h_min: 102
   s_max: 255
   s_min: 98
   v_max: 255
   v_min: 0
   erosions: 2
   dilations: 2
   width: 64
   height: 64
   x_offset: 288
   y_offset: 178
   percent_min: 50
   percent_max: 100
camera2_settings:
   h_max: 179
   h_min: 0
   s_max: 255
   s_min: 0
   v_max: 255
   v_min: 0
   erosions: 0
   dilations: 0
   width: 64
   height: 64
   x_offset: 288
   y_offset: 178
   percent_min: 0
   percent_max: 0
